# Generated by Django 5.2.14 on 2026-05-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banks',
            field=models.ManyToManyField(to='webapp.bank'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cellphone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='surname',
            field=models.CharField(max_length=50),
        ),
    ]
