# Generated by Django 5.2.14 on 2026-05-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_post_banks_alter_post_cellphone_alter_post_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Register',
        ),
    ]
