# Generated by Django 5.2.14 on 2026-06-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_post_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionId', models.CharField(max_length=1000, unique=True)),
                ('TimeDate', models.DateTimeField()),
                ('CellPhone', models.CharField(max_length=10)),
                ('Receiver', models.CharField(max_length=50)),
                ('DepositOption', models.CharField(max_length=3)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Success', models.BooleanField(default=False)),
                ('Summary', models.CharField(max_length=500)),
            ],
        ),
    ]
