# Generated by Django 5.2.14 on 2026-07-26 16:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='TimeDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='TransactionId',
            field=models.CharField(default=uuid.uuid4, max_length=1000, unique=True),
        ),
    ]
